### ISSUE TITLE
Suggest tailscale ephemeral authkeys instead of URL-based login

### ISSUE THREAD

**Issue by apenwarr** [markpash/tailscale-sidecar#1]
Cool project!

I see the instructions suggest setting a LOGIN environment variable to emit an authkey so you can do a login process the first time, then removing it after that. Instead, you might want to try ephemeral keys: https://tailscale.com/kb/1111/ephemeral-nodes/ which are often better when spinning up connections programmatically.

Hope that helps!

**Comment by markpash** [comment]
> Cool project!

Thanks! Awesome service you all offer!

> I see the instructions suggest setting a LOGIN environment variable to emit an authkey so you can do a login process the first time, then removing it after that. Instead, you might want to try ephemeral keys: https://tailscale.com/kb/1111/ephemeral-nodes/ which are often better when spinning up connections programmatically.

Great, but I'm curious how I can use that as this project uses tailscale as a library, so how would I provide the key to it? Is there a special env var I can set with the key which will authenticate the instance?

**Comment by markpash** [comment]
I see authkey support was added as part of tsnet in here https://github.com/tailscale/tailscale/pull/2613
I'll keep this issue open until I get around to updating the deps and docs to reflect this new ability.

**Comment by markpash** [comment]
> I see authkey support was added as part of tsnet in here [tailscale/tailscale#2613](https://github.com/tailscale/tailscale/pull/2613)
> I'll keep this issue open until I get around to updating the deps and docs to reflect this new ability.

This is now done :)
